USE kleague;

DESCRIBE PLAYER;
DESCRIBE TEAM;
DESCRIBE STADIUM;
DESCRIBE SCHEDULE;

SELECT * FROM PLAYER;

-------------------------------------------
-- 고급질의 문제 풀이
-------------------------------------------
--------------- 1번 예제 ---------------
SELECT T.TEAM_ID, MAX(S.SCHE_DATE)
FROM TEAM T JOIN SCHEDULE S ON T.TEAM_ID = S.HOMETEAM_ID OR T.TEAM_ID = S.AWAYTEAM_ID
GROUP BY T.TEAM_ID;


--------------- 2번 예제 ---------------
WITH TEMP AS (SELECT T.HOMETEAM_ID, MAX(T.HOME_SCORE - T.AWAY_SCORE) AS MAX_GAP
			  FROM SCHEDULE T
              GROUP BY T.HOMETEAM_ID),
TEMP2 AS (SELECT S.HOMETEAM_ID, S.AWAYTEAM_ID, S.SCHE_DATE, S.STADIUM_ID,
					 (S.HOME_SCORE - S.AWAY_SCORE) AS SCORE_GAP,
                     CONCAT(S.HOME_SCORE, ':', S.AWAY_SCORE) AS GAME_RESULT
				FROM SCHEDULE S)
SELECT T2.HOMETEAM_ID, T2.AWAYTEAM_ID, T2.SCHE_DATE, T2.STADIUM_ID, T2.SCORE_GAP, T2.GAME_RESULT
FROM TEMP2 T2 JOIN TEMP T ON T.HOMETEAM_ID = T2.HOMETEAM_ID AND T.MAX_GAP = T2.SCORE_GAP;


--------------- 3번 예제 ---------------
WITH TEMP AS ( SELECT W.TEAM_ID, W.TEAM_NAME, COUNT(Q.PLAYER_ID) COUNT
				FROM PLAYER Q JOIN TEAM W USING(TEAM_ID)
				WHERE Q.POSITION = 'GK'
				GROUP BY Q.TEAM_ID )
SELECT T.TEAM_ID, T.TEAM_NAME, COUNT(P.PLAYER_ID) ALL_NUM, T.COUNT AS GK_NUM
FROM TEMP T JOIN PLAYER P ON T.TEAM_ID = P.TEAM_ID
WHERE T.COUNT >= 4
GROUP BY T.TEAM_NAME;


--------------- 4번 예제 ---------------
WITH TEMP AS (SELECT HOMETEAM_ID, (HOME_SCORE - AWAY_SCORE) AS GAP
			  FROM SCHEDULE )
SELECT HOMETEAM_ID
FROM TEMP
WHERE HOMETEAM_ID NOT IN ( SELECT HOMETEAM_ID
						   FROM TEMP
						   WHERE GAP < 0 )
GROUP BY HOMETEAM_ID;


--------------- 5번 예제 ---------------
WITH TEMP AS ( SELECT HOMETEAM_ID, AWAYTEAM_ID, (HOME_SCORE - AWAY_SCORE) AS HOME,
					  (AWAY_SCORE - HOME_SCORE) AS AWAY
				FROM SCHEDULE ),
D1 AS ( SELECT HOMETEAM_ID, COUNT(HOME) B
		FROM ( SELECT HOMETEAM_ID, HOME
			   FROM TEMP
			   WHERE HOME = 0 ) AS T1
		GROUP BY HOMETEAM_ID ),
D2 AS ( SELECT AWAYTEAM_ID, COUNT(AWAY) BB
		FROM ( SELECT AWAYTEAM_ID, AWAY
			   FROM TEMP
			   WHERE AWAY = 0 ) AS T2
		GROUP BY AWAYTEAM_ID ),
W1 AS ( SELECT HOMETEAM_ID, COUNT(HOME) B
		FROM ( SELECT HOMETEAM_ID, HOME
			   FROM TEMP
			   WHERE HOME > 0 ) AS T1
		GROUP BY HOMETEAM_ID ),
W2 AS ( SELECT AWAYTEAM_ID, COUNT(AWAY) BB
		FROM ( SELECT AWAYTEAM_ID, AWAY
			   FROM TEMP
			   WHERE AWAY > 0 ) AS T2
		GROUP BY AWAYTEAM_ID ),
L1 AS ( SELECT HOMETEAM_ID, COUNT(HOME) B
		FROM ( SELECT HOMETEAM_ID, HOME
			   FROM TEMP
			   WHERE HOME < 0 ) AS T1
		GROUP BY HOMETEAM_ID ),
L2 AS ( SELECT AWAYTEAM_ID, COUNT(AWAY) BB
		FROM ( SELECT AWAYTEAM_ID, AWAY
			   FROM TEMP
			   WHERE AWAY < 0 ) AS T2
		GROUP BY AWAYTEAM_ID ),
DRAW AS ( SELECT D1.HOMETEAM_ID TEAM_ID, (D1.B + COALESCE(D2.BB,0)) AS DRAW
		  FROM D1 LEFT JOIN D2 ON D1.HOMETEAM_ID = D2.AWAYTEAM_ID ),
WIN AS ( SELECT W1.HOMETEAM_ID TEAM_ID, (W1.B + COALESCE(W2.BB,0)) AS WIN
		  FROM W1 LEFT JOIN W2 ON W1.HOMETEAM_ID = W2.AWAYTEAM_ID ),
LOSE AS ( SELECT L1.HOMETEAM_ID TEAM_ID, (L1.B + COALESCE(L2.BB,0)) AS LOSE
		  FROM L1 LEFT JOIN L2 ON L1.HOMETEAM_ID = L2.AWAYTEAM_ID )
SELECT TEAM_ID, WIN, DRAW, LOSE, (WIN + DRAW + LOSE) AS 'TOTAL PLAY'
FROM DRAW JOIN WIN USING(TEAM_ID) JOIN LOSE USING(TEAM_ID);
